### ISSUE TITLE
No Module available named Generation

### ISSUE THREAD

**Issue by bazil852** [SanELmoumni/Scheduling-problem-in-operational-research-Dynamic-programming-Metaheuristic-VNS-solutions.#2]
Hey really like the work you did here. 
one thing I couldn't find any module available named Generation.
Could you help me with that?

**Comment by SanELmoumni** [comment]
Hello;
Thank you for mentioning this, I forgot to add the script "generation" that generates random input data. 
I just pushed it. 
I'll close the issue for now.
Feel free to contact if there's any other issue.
